export default function Github() {
  return (
    <div>
      <p>Use this JSON payload</p>
      <textarea
        readOnly
        style={{
          background: "black",
          padding: "0.5rem",
          width: "100%",
          height: "30rem",
        }}
      >
        {`{
      "action": "closed",
      "issue": {
        "url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/issues/187",
        "repository_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova",
        "labels_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/issues/187/labels{/name}",
        "comments_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/issues/187/comments",
        "events_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/issues/187/events",
        "html_url": "https://github.com/Thorium-Sim/thorium-nova/issues/187",
        "id": 1097046223,
        "node_id": "I_kwDOEMMgzc5BY5jP",
        "number": 187,
        "title": "Star Map - Enable navigation between the interstellar and solar system views",
        "user": {
          "login": "alexanderson1993",
          "id": 6558157,
          "node_id": "MDQ6VXNlcjY1NTgxNTc=",
          "avatar_url": "https://avatars.githubusercontent.com/u/6558157?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/alexanderson1993",
          "html_url": "https://github.com/alexanderson1993",
          "followers_url": "https://api.github.com/users/alexanderson1993/followers",
          "following_url": "https://api.github.com/users/alexanderson1993/following{/other_user}",
          "gists_url": "https://api.github.com/users/alexanderson1993/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/alexanderson1993/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/alexanderson1993/subscriptions",
          "organizations_url": "https://api.github.com/users/alexanderson1993/orgs",
          "repos_url": "https://api.github.com/users/alexanderson1993/repos",
          "events_url": "https://api.github.com/users/alexanderson1993/events{/privacy}",
          "received_events_url": "https://api.github.com/users/alexanderson1993/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [
    
        ],
        "state": "closed",
        "locked": false,
        "assignee": {
          "login": "alexanderson1993",
          "id": 6558157,
          "node_id": "MDQ6VXNlcjY1NTgxNTc=",
          "avatar_url": "https://avatars.githubusercontent.com/u/6558157?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/alexanderson1993",
          "html_url": "https://github.com/alexanderson1993",
          "followers_url": "https://api.github.com/users/alexanderson1993/followers",
          "following_url": "https://api.github.com/users/alexanderson1993/following{/other_user}",
          "gists_url": "https://api.github.com/users/alexanderson1993/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/alexanderson1993/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/alexanderson1993/subscriptions",
          "organizations_url": "https://api.github.com/users/alexanderson1993/orgs",
          "repos_url": "https://api.github.com/users/alexanderson1993/repos",
          "events_url": "https://api.github.com/users/alexanderson1993/events{/privacy}",
          "received_events_url": "https://api.github.com/users/alexanderson1993/received_events",
          "type": "User",
          "site_admin": false
        },
        "assignees": [
          {
            "login": "alexanderson1993",
            "id": 6558157,
            "node_id": "MDQ6VXNlcjY1NTgxNTc=",
            "avatar_url": "https://avatars.githubusercontent.com/u/6558157?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/alexanderson1993",
            "html_url": "https://github.com/alexanderson1993",
            "followers_url": "https://api.github.com/users/alexanderson1993/followers",
            "following_url": "https://api.github.com/users/alexanderson1993/following{/other_user}",
            "gists_url": "https://api.github.com/users/alexanderson1993/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/alexanderson1993/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/alexanderson1993/subscriptions",
            "organizations_url": "https://api.github.com/users/alexanderson1993/orgs",
            "repos_url": "https://api.github.com/users/alexanderson1993/repos",
            "events_url": "https://api.github.com/users/alexanderson1993/events{/privacy}",
            "received_events_url": "https://api.github.com/users/alexanderson1993/received_events",
            "type": "User",
            "site_admin": false
          }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2022-01-08T22:08:09Z",
        "updated_at": "2022-02-11T19:04:25Z",
        "closed_at": "2022-02-11T19:04:25Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "body": null,
        "reactions": {
          "url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/issues/187/reactions",
          "total_count": 0,
          "+1": 0,
          "-1": 0,
          "laugh": 0,
          "hooray": 0,
          "confused": 0,
          "heart": 0,
          "rocket": 0,
          "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/issues/187/timeline",
        "performed_via_github_app": null
      },
      "repository": {
        "id": 281223373,
        "node_id": "MDEwOlJlcG9zaXRvcnkyODEyMjMzNzM=",
        "name": "thorium-nova",
        "full_name": "Thorium-Sim/thorium-nova",
        "private": false,
        "owner": {
          "login": "Thorium-Sim",
          "id": 23285942,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjIzMjg1OTQy",
          "avatar_url": "https://avatars.githubusercontent.com/u/23285942?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Thorium-Sim",
          "html_url": "https://github.com/Thorium-Sim",
          "followers_url": "https://api.github.com/users/Thorium-Sim/followers",
          "following_url": "https://api.github.com/users/Thorium-Sim/following{/other_user}",
          "gists_url": "https://api.github.com/users/Thorium-Sim/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Thorium-Sim/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Thorium-Sim/subscriptions",
          "organizations_url": "https://api.github.com/users/Thorium-Sim/orgs",
          "repos_url": "https://api.github.com/users/Thorium-Sim/repos",
          "events_url": "https://api.github.com/users/Thorium-Sim/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Thorium-Sim/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/Thorium-Sim/thorium-nova",
        "description": "Next-generation Spaceship Controls",
        "fork": false,
        "url": "https://api.github.com/repos/Thorium-Sim/thorium-nova",
        "forks_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/forks",
        "keys_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/teams",
        "hooks_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/hooks",
        "issue_events_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/events",
        "assignees_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/tags",
        "blobs_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/languages",
        "stargazers_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/stargazers",
        "contributors_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/contributors",
        "subscribers_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/subscribers",
        "subscription_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/subscription",
        "commits_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/merges",
        "archive_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/downloads",
        "issues_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/labels{/name}",
        "releases_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Thorium-Sim/thorium-nova/deployments",
        "created_at": "2020-07-20T20:52:24Z",
        "updated_at": "2022-01-24T16:41:21Z",
        "pushed_at": "2022-02-11T19:04:24Z",
        "git_url": "git://github.com/Thorium-Sim/thorium-nova.git",
        "ssh_url": "git@github.com:Thorium-Sim/thorium-nova.git",
        "clone_url": "https://github.com/Thorium-Sim/thorium-nova.git",
        "svn_url": "https://github.com/Thorium-Sim/thorium-nova",
        "homepage": "https://thoriumsim.com",
        "size": 42301,
        "stargazers_count": 34,
        "watchers_count": 34,
        "language": "TypeScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "forks_count": 2,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 60,
        "license": {
          "key": "apache-2.0",
          "name": "Apache License 2.0",
          "spdx_id": "Apache-2.0",
          "url": "https://api.github.com/licenses/apache-2.0",
          "node_id": "MDc6TGljZW5zZTI="
        },
        "allow_forking": true,
        "is_template": false,
        "topics": [
          "hacktoberfest",
          "simulation"
        ],
        "visibility": "public",
        "forks": 2,
        "open_issues": 60,
        "watchers": 34,
        "default_branch": "develop"
      },
      "organization": {
        "login": "Thorium-Sim",
        "id": 23285942,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjIzMjg1OTQy",
        "url": "https://api.github.com/orgs/Thorium-Sim",
        "repos_url": "https://api.github.com/orgs/Thorium-Sim/repos",
        "events_url": "https://api.github.com/orgs/Thorium-Sim/events",
        "hooks_url": "https://api.github.com/orgs/Thorium-Sim/hooks",
        "issues_url": "https://api.github.com/orgs/Thorium-Sim/issues",
        "members_url": "https://api.github.com/orgs/Thorium-Sim/members{/member}",
        "public_members_url": "https://api.github.com/orgs/Thorium-Sim/public_members{/member}",
        "avatar_url": "https://avatars.githubusercontent.com/u/23285942?v=4",
        "description": "Next-generation space simulator controls"
      },
      "sender": {
        "login": "alexanderson1993",
        "id": 6558157,
        "node_id": "MDQ6VXNlcjY1NTgxNTc=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6558157?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/alexanderson1993",
        "html_url": "https://github.com/alexanderson1993",
        "followers_url": "https://api.github.com/users/alexanderson1993/followers",
        "following_url": "https://api.github.com/users/alexanderson1993/following{/other_user}",
        "gists_url": "https://api.github.com/users/alexanderson1993/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/alexanderson1993/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/alexanderson1993/subscriptions",
        "organizations_url": "https://api.github.com/users/alexanderson1993/orgs",
        "repos_url": "https://api.github.com/users/alexanderson1993/repos",
        "events_url": "https://api.github.com/users/alexanderson1993/events{/privacy}",
        "received_events_url": "https://api.github.com/users/alexanderson1993/received_events",
        "type": "User",
        "site_admin": false
      }
    }`}
      </textarea>
    </div>
  );
}
